version: "3.9"
services:
  backend:
    build:
      context: ./backend
    image: kitbash/backend:dev
    environment:
      - HTTP_PORT=8080
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: kitbash/frontend:dev
    depends_on:
      - backend
    ports:
      - "8081:80"
    restart: unless-stopped

networks:
  default:
    name: kitbash-net

