name: Go Tests

on:
  push:
    paths:
      - 'backend/**'
      - '.github/workflows/go-tests.yml'
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/go-tests.yml'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run Go tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: backend/go.mod
          cache: true
          cache-dependency-path: backend/go.sum

      - name: Test
        run: go test -race -v ./...

